name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-job:

    runs-on: ubuntu-latest
    
    services:
    
      postgres:
        
        image: postgis/postgis:10-2.5
        
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: 'dummyproject'
        ports:
          - 5432:5432
        
        # Set health checks to wait until postgres has started

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Connect to PostgreSQL
    - name: Run tests
      run: sbt test
